#!/bin/sh
set -eu

# Regenerate the Memento citation inventory from the two frozen pins.
# File-and-line citations are checked and hashed. Git-history and directory
# citations are kept in a manual-check section so they cannot disappear quietly.

BOOK_ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
MEMENTO_ROOT=${MEMENTO_ROOT:-"$HOME/Downloads/MEMENTO"}
PIN_FILE="$BOOK_ROOT/research/MEMENTO-PIN"
OUTPUT_FILE="$BOOK_ROOT/research/CITATIONS.md"

python3 - "$BOOK_ROOT" "$MEMENTO_ROOT" "$PIN_FILE" "$OUTPUT_FILE" <<'PY'
from __future__ import annotations

import hashlib
import html
import re
import subprocess
import sys
from pathlib import Path

book_root = Path(sys.argv[1])
memento_root = Path(sys.argv[2])
pin_file = Path(sys.argv[3])
output_file = Path(sys.argv[4])

pins: dict[str, str] = {}
for raw in pin_file.read_text(encoding="utf-8").splitlines():
    raw = raw.strip()
    if not raw or raw.startswith("#"):
        continue
    bits = raw.split()
    if len(bits) >= 2 and bits[0] in {"web", "native"}:
        pins[bits[0]] = bits[1]

if set(pins) != {"web", "native"}:
    raise SystemExit("MEMENTO-PIN must contain web and native pins")

path_pattern = re.compile(
    r"(?P<path>"
    r"(?:memento-app|memento-native|supabase|MIGRATION|\.github)/[^:<>()]+?"
    r"|CLAUDE\.md|DECISIONS\.md|BACKEND_EMERGENCY_PLAYBOOK\.md"
    r"|Open Memento \(new modular\)\.command"
    r"):(?P<lines>\d+(?:-\d+)?(?:\s*(?:,|and)\s*\d+(?:-\d+)?)*)"
)
src_pattern = re.compile(
    r'<(?:div|span) class="src">(.*?)</(?:div|span)>', re.DOTALL
)
tag_pattern = re.compile(r"<[^>]+>")


def git_show(commit: str, path: str) -> str:
    proc = subprocess.run(
        ["git", "show", f"{commit}:{path}"],
        cwd=memento_root,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if proc.returncode:
        raise RuntimeError(f"{commit}:{path}: {proc.stderr.strip()}")
    return proc.stdout


def line_numbers(spec: str) -> list[int]:
    values: list[int] = []
    for part in re.split(r"\s*(?:,|and)\s*", spec):
        if "-" in part:
            start, end = (int(v) for v in part.split("-", 1))
            if end < start:
                raise ValueError(f"backwards line range {spec}")
            values.extend(range(start, end + 1))
        else:
            values.append(int(part))
    return values


rows: list[tuple[str, str, str, str, str]] = []
manual: list[tuple[str, str, str]] = []
errors: list[str] = []

for chapter in sorted((book_root / "chapters").glob("[0-3][0-9]-*.html")):
    if chapter.name.startswith("00-"):
        continue
    chapter_number = chapter.name[:2]
    source = chapter.read_text(encoding="utf-8")
    for raw_match in src_pattern.finditer(source):
        citation = html.unescape(tag_pattern.sub("", raw_match.group(1)))
        citation = " ".join(citation.split())
        pin_name = "native" if "native pin" in citation else "web" if "web pin" in citation else ""
        if not pin_name:
            continue
        if citation.startswith("git show "):
            manual.append((chapter_number, pin_name, citation))
            continue
        matches = list(path_pattern.finditer(citation))
        if not matches:
            manual.append((chapter_number, pin_name, citation))
            continue
        for match in matches:
            path = match.group("path").strip()
            spec = match.group("lines").strip()
            try:
                content = git_show(pins[pin_name], path)
                lines = content.splitlines(keepends=True)
                wanted = line_numbers(spec)
                if not wanted or min(wanted) < 1 or max(wanted) > len(lines):
                    raise ValueError(f"range {spec} outside 1-{len(lines)}")
                selected = "".join(lines[number - 1] for number in wanted).encode("utf-8")
                digest = hashlib.sha256(selected).hexdigest()
                rows.append((chapter_number, path, spec, pin_name, digest))
            except (RuntimeError, ValueError) as exc:
                errors.append(f"chapter {chapter_number}: {exc}")

rows.sort(key=lambda row: (int(row[0]), row[1], row[2]))
manual.sort(key=lambda row: (int(row[0]), row[2]))

parts = [
    "# Memento citation inventory",
    "",
    "Generated by `tools/cite-check.sh` from `research/MEMENTO-PIN`.",
    "The SHA-256 value covers the cited lines only, in the order listed, including their line endings.",
    "",
    f"- Web pin: `{pins['web']}`",
    f"- Native pin: `{pins['native']}`",
    "",
    "## Verified file ranges",
    "",
    "| Chapter | Path | Lines | Pin | SHA-256 |",
    "|---:|---|---:|---|---|",
]
for chapter, path, spec, pin_name, digest in rows:
    parts.append(f"| {int(chapter)} | `{path}` | `{spec}` | `{pin_name} {pins[pin_name]}` | `{digest}` |")

parts.extend([
    "",
    "## Manual citations",
    "",
    "These cite git history, directory inventories, generated command output, or prose anchors rather than one file range. They stay visible here and require the chapter fact-check to verify them.",
    "",
    "| Chapter | Pin | Citation |",
    "|---:|---|---|",
])
for chapter, pin_name, citation in manual:
    safe = citation.replace("|", "\\|")
    parts.append(f"| {int(chapter)} | `{pin_name} {pins[pin_name]}` | {safe} |")

parts.append("")
output_file.write_text("\n".join(parts), encoding="utf-8")

if errors:
    for error in errors:
        print(error, file=sys.stderr)
    raise SystemExit(1)

print(f"verified {len(rows)} file ranges; listed {len(manual)} manual citations")
PY
